version: "2"

services:
  web:
    build: .
    command: yarn run docker
    environment:
      NODE_ENV: development
    expose:
      - "8080"
    ports:
      - 8080:8080
    volumes:
      - .:/app
